<?php

namespace AppBundle\Repository;

/**
 * UserInfosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserInfosRepository extends \Doctrine\ORM\EntityRepository
{
}
